Added needed dependency for argument parsing
PM-Dungeon/pmdungeon-old pull request #79
Opened 2021-06-21 16:05 UTC by Kushurando

Added default values to be overwritten using the launch arguments.

2021-06-22 10:42 UTC, AMatutat submitted a review, later dismissed
Looks good.
Have some small change requests. 
Still have to test it.

2021-06-22 10:42 UTC, AMatutat commented on src/de/pmdungeon/desktop/DesktopLauncher.java
remove empty line

2021-06-22 10:42 UTC, AMatutat commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +     * @param args Launch parameters to override the default values
we should add some sort of documentation for that in the javadoc

2021-06-22 10:42 UTC, AMatutat commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +        HelpFormatter formatter = new HelpFormatter();
autoformat over the code once more

2021-06-22 10:42 UTC, AMatutat commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +    	Option ptl = new Option("ptl", "pathToLevel", true, "path to level");
guess we should rename `pathToLevel` to `levelFolder` or something.

2021-06-22 10:42 UTC, AMatutat commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +    	Option fps = new Option("fr", "framerate", true, "framerate");
can we use `fps` instead of `fr`?

2021-06-22 10:42 UTC, AMatutat commented on src/de/pmdungeon/tools/Constants.java
> +		Constants.startLevel = Constants.pathToLevel+startLevel;
Maybe do `Constants.pathToLevel+"/"+startLevel` ?
I guess most people will not add a `/` at the end of their pathToLevel.

2021-06-22 11:44 UTC, AMatutat commented on src/de/pmdungeon/tools/Constants.java
> +	private static String startLevel = Constants.pathToLevel+"small_dungeon.json";
Run into a bug:
If you want to use all default arguments, then startLevel is set to `nullsmall dungeon.json` because pathToLevel is not initialized. Swap line 23 and 28 and all should be good.

2021-06-22 11:56 UTC, AMatutat commented
Ok maybe I´m stupid but shouldn´t
` mvn exec:java -Dexec.mainClass=de.pmdungeon.desktop.Main -Dexec.args="'fs true'" ` 
pass the command line argument?  (fs is just for example) 
My Main: 
```
public static void main (String[]args){

    DesktopLauncher.run(new MainController(), args);
}
```

2021-06-22 12:14 UTC, AMatutat commented on src/de/pmdungeon/tools/Constants.java
> +		Constants.startLevel = Constants.pathToLevel+startLevel;
Sounds good. This should allow "path" and "path/"

2021-06-22 12:54 UTC, cagix requested changes
A few small changes and it should be fine. And please have the code formatted again with the Editorconfig plugin activated!

2021-06-22 12:54 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +    	Option ptl = new Option("ptl", "pathToLevel", true, "path to level");
also: all other options have full names. this and the next two options have abbreviations as identifiers. this should be consistent.

2021-06-22 12:54 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +				e.printStackTrace();
Okay, that's just ugly. Something meaningful should happen here!

2021-06-22 12:54 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +				e.printStackTrace();
Okay, that's just ugly. Something meaningful should happen here!

2021-06-22 12:54 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +				e.printStackTrace();
Okay, that's just ugly. Something meaningful should happen here!

2021-06-22 12:54 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +				e.printStackTrace();
Okay, that's just ugly. Something meaningful should happen here!

2021-06-22 12:54 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +				e.printStackTrace();
Okay, that's just ugly. Something meaningful should happen here!

2021-06-22 12:54 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +				e.printStackTrace();
Okay, that's just ugly. Something meaningful should happen here!

2021-06-22 12:54 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +        }else {
format?

2021-06-22 12:54 UTC, cagix commented on src/de/pmdungeon/game/Controller/LevelController.java
>          }
no `default`?

2021-06-22 12:54 UTC, cagix commented on src/de/pmdungeon/tools/Constants.java
>  public class Constants {
Javadoc for public class missing ...

2021-06-22 12:54 UTC, cagix commented on src/de/pmdungeon/tools/Constants.java
> +	private static String startLevel = Constants.pathToLevel+"small_dungeon.json";
also: format!

2021-06-22 12:54 UTC, cagix commented on src/de/pmdungeon/tools/Constants.java
> +    public static void setResizable(boolean resizable) {
format?!

2021-06-22 13:04 UTC, cagix commented
@AMatutat Maybe I'm too tired right now, but on a conceptual level the code somehow just feels wrong. We encapsulate a number of constants that don't really belong together into a shared class, which is usually considered a no-go ;)  ... Okay, but it kind of makes sense here, to have all constants in a shared placed.

But then we add a lot of plain getters and setters, which do nothing more than just return the value. And as static methods, too ... 

I'm not sure, but wouldn't it make more sense to make the "constants" non-constant then and just `static public`? Whoever then wants to change them simply makes an assignment at their own risk?

2021-06-22 13:11 UTC, Kushurando commented
> @AMatutat Maybe I'm too tired right now, but on a conceptual level the code somehow just feels wrong. We encapsulate a number of constants that don't really belong together into a shared class, which is usually considered a no-go ;) ... Okay, but it kind of makes sense here, to have all constants in a shared placed.
> 
> But then we add a lot of plain getters and setters, which do nothing more than just return the value. And as static methods, too ...
> 
> I'm not sure, but wouldn't it make more sense to make the "constants" non-constant then and just `static public`? Whoever then wants to change them simply makes an assignment at their own risk?

fair point, I don't remember why exactly I did the getter setter thing, but I can change it to use the static public variables instead.

(also sorry on the formatting, forgot to run a formatter over it.)

2021-06-22 13:59 UTC, AMatutat commented on src/de/pmdungeon/game/Controller/LevelController.java
>          }
No default needed. This is the level circle of hell and nobody can touch it. In a brighter future this will be replaced by an level generator.

2021-06-22 14:08 UTC, AMatutat commented
> We encapsulate a number of constants that don't really belong together into a shared class, which is usually considered a no-go ;)

Would disagree on that one. But other discussion. 


> But then we add a lot of plain getters and setters, which do nothing more than just return the value. And as static methods, too ...

> I'm not sure, but wouldn't it make more sense to make the "constants" non-constant then and just static public? Whoever then wants to change them simply makes an assignment at their own risk?

To be honest, i like both ways. Only static public is more "clean" but getter and aetter are more safe. On the other hand, static setters feels just wrong. Not sure about that one. 

Other thoug: Our constants are no longer constants, they are Setup-Parameter(?), maybe we should rename the class.

2021-06-22 15:06 UTC, cagix commented
> To be honest, i like both ways. Only static public is more "clean" but getter and setter are more safe. On the other hand, static setters feels just wrong. Not sure about that one.

it's quite a lot of boiler plate code just to access some pseudo-constants ;) ... i like the way this is handled in Ruby.

alas, if we were using Java 14 (or later), this could be a perfect use case for the new record syntax ... :)

> Other thoug: Our constants are no longer constants, they are Setup-Parameter(?), maybe we should rename the class.

like this idea :)

2021-06-25 16:39 UTC, Kushurando commented
Still have to fix the try catch blocks that Gips pointed out.

Also, I am suddenly getting an error when trying to launch this, namely a class not found exception caused by the ScreenAdapter in mainController, I am not sure why it is throwing that

Lastly, if anyone has better suggestions for the variable startLevelFile, please let me know, I don't really like the name but couldn't think of anything better.

2021-06-27 19:00 UTC, Tobias321 commented
> Lastly, if anyone has better suggestions for the variable startLevelFile, please let me know, I don't really like the name but couldn't think of anything better.

firstLevelFile and firstLevelPath, but that is quite nearly similar.

2021-06-27 19:04 UTC, Tobias321 commented
> Also, I am getting an error when trying to launch this, namely a class not found exception caused by the ScreenAdapter in mainController, I am not sure why it is throwing that, and I am pretty sure I didn't get it before.

Sounds like an exception i got before i have fixed the imports for gradle, maven, ant... Please rebase your branch onto the newest master, delete the build dirs and compile again.

2021-06-27 19:07 UTC, Tobias321 commented
> Still have to fix the try catch blocks that Gips pointed out.

In the catch part you could provide default values for the attributes...

2021-06-30 09:07 UTC, Tobias321 commented
@cagix @Kushurando Sometimes you can edit a PR branch and sometimes not, I still haven't fully understand GitHub's logic behind this. I think, the simplest way is to save your changes, `git checkout master`, `git clean -fd`, `git pull` and to create a new branch from current master and to transfer your changes to the branch. Then you can try to edit the PR branch or create a new PR. Hope that helps.

2021-07-02 15:52 UTC, Kushurando commented
Code wise this should be done now I think.

2021-07-02 16:03 UTC, Tobias321 requested changes
is this a new branch based on current master?

2021-07-02 16:08 UTC, Kushurando commented
> is this a new branch based on current master?

I rebased the previous branch.

2021-07-02 16:09 UTC, Kushurando commented on .gitignore
> +/bin/
fixed

2021-07-02 16:10 UTC, Kushurando commented on pom.xml
> +
I got no idea how to do that with ant, and gradle didn't like it the previous time I tried, so uh, if you would be so kind?

2021-07-02 16:21 UTC, Tobias321 commented
> > is this a new branch based on current master?
> 
> I rebased the previous branch.

gitk looks ok 👍🏻

2021-07-02 16:22 UTC, Tobias321 commented on pom.xml
> +
> if you would be so kind?

ok 👍🏻

2021-07-02 16:31 UTC, Tobias321 commented
Dependency update: done 🙂

2021-07-02 16:32 UTC, Kushurando commented
> Dependency update: done 🙂

thanks

2021-07-02 18:59 UTC, Tobias321 approved these changes
lgtm

2021-07-02 19:35 UTC, cagix requested changes
👍 some minor improvements recommended

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +            System.out.println(e.getMessage());
shouldn't this be a call to a logger?

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +                System.out.println(
dito

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +                System.out.println(
dito

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +                System.out.println("Invalid Path to level folder. " + e.getMessage() + "Using default value instead.");
dito

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +                System.out.println("Invalid file name/path for starting level. " + e.getMessage()
dito

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +                System.out.println("Invalid Parameter for option Frames per Second. " + e.getMessage()
dito

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +                System.out.println("Invalid Parameter for option Virtual Height. " + e.getMessage()
dito

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/game/Controller/EntityController.java
> +            this.dungeonEntities.add(entity);
code style: please use curly brackets around statement

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/game/Controller/EntityController.java
> +            this.dungeonEntities.remove(entity);
dito

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/game/Controller/EntityController.java
> +        if (!dungeonEntities.contains(entity))
shouldn't be `dungeonEntities` a set, i.e. it shouldn't be necessary to check if `entity` is already a member?

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/game/Controller/EntityController.java
> +        if (dungeonEntities.contains(entity))
dito

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/game/Controller/LevelController.java
> +            return;
code style: would inverse the logic, i.e. `if (! ...) { ... render ...}` ...

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/graphic/HUD.java
> +            this.hudElements.remove(element);
woul recommend to use curly brackets

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/graphic/HUD.java
> +        if (usePixelSystem)
one exit per function: if (not ...) {do setup}

2021-07-02 19:35 UTC, cagix commented on src/de/pmdungeon/graphic/HUD.java
> +        parameter.borderWidth = 1;
magic int again?

2021-07-02 19:42 UTC, Kushurando commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +            System.out.println(e.getMessage());
Was the logger implemented in this? I thought we left that for the students to implement.

2021-07-02 19:50 UTC, Kushurando commented on src/de/pmdungeon/graphic/HUD.java
> +        parameter.borderWidth = 1;
oh, I took the wrong stuff, that was meant to take the changed values from the master branch

2021-07-02 19:51 UTC, Kushurando commented on src/de/pmdungeon/graphic/HUD.java
> +        parameter.borderWidth = 1;
all of the things in the hud, well, most of it, how do I change that though

2021-07-02 19:59 UTC, Kushurando commented on src/de/pmdungeon/graphic/HUD.java
> +        parameter.borderWidth = 1;
manually adjusted that now

2021-07-02 20:45 UTC, Kushurando commented on src/de/pmdungeon/graphic/HUD.java
> +            this.hudElements.remove(element);
that should've been the case already, can you check the new commit if it's there?

2021-07-02 20:45 UTC, Kushurando commented on src/de/pmdungeon/graphic/HUD.java
> +        if (usePixelSystem)
changed it to mirror the master, which it was meant to do to begin with, mistake on my part

2021-07-03 09:52 UTC, Tobias321 commented
Regarding "code style/curly brackets": You can add that in eclipse's save actions:

![Unbenannt](https://user-images.githubusercontent.com/85501570/124350402-e119ce00-dbf4-11eb-9605-4ea3e4354129.png)

2021-07-03 11:08 UTC, cagix commented
yeah, question is, what happens during @AMatutat 's github action? (auto format)

2021-07-03 11:11 UTC, Tobias321 commented
> yeah, question is, what happens during @AMatutat 's github action? (auto format)

afaik, both settings are applied :)

2021-07-03 16:58 UTC, cagix commented on src/de/pmdungeon/desktop/DesktopLauncher.java
> +            System.out.println(e.getMessage());
hmmm, good point. i'd say, if they really look into this, they probably are able to use the logger by themselves... and then we really shouldn't give a "bad" example ;)

@AMatutat what's your opinion?

2021-07-03 17:19 UTC, Kushurando commented
> Regarding "code style/curly brackets": You can add that in eclipse's save actions:

Can't find that option, but they already were in a code block to begin with when I committed it.

2021-07-03 18:43 UTC, Tobias321 commented
> Can't find that option,

```diff
- Note the red markings
```
😉 
you can find Preferences under Window -> Preferences. 

> but they already were in a code block to begin with when I committed it.

👍🏻 🙂

2021-07-05 14:18 UTC, AMatutat requested changes

2021-07-05 14:18 UTC, AMatutat commented on src/de/pmdungeon/game/Controller/EntityController.java
> +        this.dungeonEntities.remove(entity);
why?

2021-07-05 14:18 UTC, AMatutat commented on src/de/pmdungeon/game/Controller/EntityController.java
> +        this.dungeonEntities.add(entity);
why?

2021-07-05 14:27 UTC, Kushurando commented on src/de/pmdungeon/game/Controller/EntityController.java
> +        this.dungeonEntities.remove(entity);
it's a set, it automatically checks whether it's a member or not, no need to double check

2021-07-05 14:41 UTC, Kushurando commented on src/de/pmdungeon/game/Controller/EntityController.java
> +        this.dungeonEntities.remove(entity);
wait nevermind, it's not, I was thinking of something else

2021-07-07 15:09 UTC, CrappyAlgorithm commented on src/de/pmdungeon/game/Controller/LevelController.java
> +            return;
Either I'm missing something or the else block is unnecessary.

2021-07-25 15:08 UTC, Kushurando commented
Right, so, I didn't have much time the last few weeks cause of exams, so I did it now, I believe it should work now(except that I am getting an error saying that the dungeonworld is null, but I get that on the master branch as well, and when I stop the call of the actual game it works, very scuffed, I know)

anyway, the maven command should be as follows:

mvn exec:java -Dexec.mainClass=de.pmdungeon.desktop.Main -Dexec.args="-fs true"

note the dash, otherwise it doesn't recognize it as an argument(also the single '' were superfluous and might be part of the reason why it didn't work)

2021-07-25 19:57 UTC, Tobias321 commented
This branch has conflicts that must be resolved 🙁 
PR #95 has an effect on this branch
@CrappyAlgorithm has used an enum instead of switch-case in `LevelController.java`

2021-07-25 22:03 UTC, Kushurando commented
> This branch has conflicts that must be resolved 🙁
> PR #95 has an effect on this branch
> @CrappyAlgorithm has used an enum instead of switch-case in `LevelController.java`

Ah yeah, I know, I was going to resolve them once people checked whether it actually works for them now. Otherwise I'd just end up rebasing a 5th time and having to do it again later :D probably should've done it anyway.

Have you checked whether it works for you?

2021-07-26 06:28 UTC, Tobias321 commented
> Have you checked whether it works for you?

It works for me with `mvn exec:java -Dexec.mainClass=de.pmdungeon.desktop.Main -Dexec.args="-xxx true"` and I've re-request a review from the others. In any case, thanks for your work. 🙂 But, by the way,  the `commons-cli` dependency must be still added to Gradle and Ant too.

Or could the parsing be do "manually", without the `commons-cli` library?

2021-07-26 14:56 UTC, Kushurando commented
parsing it manually would take a lot of extra effort, probably best to just use the commons cli

2021-08-04 19:28 UTC, Tobias321 commented
> parsing it manually would take a lot of extra effort, probably best to just use the commons cli

ok. are you still working on this?

2021-08-04 19:47 UTC, Tobias321 submitted a review, later dismissed
lgtm, but a few changes requested

2021-08-04 19:47 UTC, Tobias321 commented on pom.xml
> +		</dependency>
- needs to add to gradle and ant too
- needs version number variables
- needs scoop compile
- should be inserted at last place

2021-08-04 19:47 UTC, Tobias321 commented on src/de/pmdungeon/graphic/HUD.java
> +        }
have you inverted the if-else logic?

2021-08-04 19:47 UTC, Tobias321 commented on src/de/pmdungeon/tools/GlobalParameters.java
> +    private static int framesPerSecond = 30;
is a frame rate of 10 better?

2021-08-04 20:02 UTC, AMatutat commented on src/de/pmdungeon/tools/GlobalParameters.java
> +    private static int framesPerSecond = 30;
Why should it?

2021-08-04 20:32 UTC, Tobias321 commented on src/de/pmdungeon/tools/GlobalParameters.java
> +    private static int framesPerSecond = 30;
> Why should it?

I had seen this in this commit 7ada5bd434e63064031b426fcede89cde8bba819 , but not recognized that was from December 2020... sorry.

2021-08-05 01:18 UTC, Kushurando commented
> > parsing it manually would take a lot of extra effort, probably best to just use the commons cli
> 
> ok. are you still working on this?

ah, no, I was waiting for the others to review the current state of it, before rebasing and merging assuming everything works.

I might do a non CLI implementation next semester or something, but not during the semester break

2021-08-05 01:21 UTC, Kushurando commented on src/de/pmdungeon/graphic/HUD.java
> +        }
I didn't touch the Hud beyond changing the parameter names to fit the new version, if this was inverted elsewhere then I'll fix that when rebasing

2021-08-05 05:07 UTC, cagix requested changes
two minor issues and one case of inverted logic ...

2021-08-05 05:07 UTC, cagix commented on src/de/pmdungeon/graphic/HUD.java
> +        }
yeah, that does look inverted when i look at the diff. that's also why i always recommend brackets in the `if` blocks, even if it's just a single statement.

2021-08-05 05:07 UTC, cagix commented on src/de/pmdungeon/graphic/HUD.java
> +}
blank line missing ... will be added automatically when merging anyway.

2021-08-05 10:32 UTC, Tobias321 commented
> but not during the semester break

is ok. i will be in standby-mode until September/October too. 😉

2021-08-05 10:41 UTC, cagix commented on src/de/pmdungeon/tools/GlobalParameters.java
> +    private static int framesPerSecond = 30;
hmmm, this was just to reduce the load in my virtual machine ... probably it is ok to go with 30fps as default ...

2021-08-05 11:02 UTC, Tobias321 commented on src/de/pmdungeon/tools/GlobalParameters.java
> +    private static int framesPerSecond = 30;
@cagix Yes, I just saw the revision comparisons of some files in Intellij and it was late. We can keep 30 fps as the default value.

2021-08-10 17:12 UTC, Tobias321 requested changes
LGTM, only some minor changes requested 👍🏻

2021-08-10 17:12 UTC, Tobias321 commented on pom.xml
> +        <pluginManagement>
should be `<plugins>`

2021-08-10 17:12 UTC, Tobias321 commented on pom.xml
> +        </pluginManagement>
should be `</plugins>`

2021-08-10 17:12 UTC, Tobias321 commented on src/de/pmdungeon/desktop/Main.java
> +}
maybe should not be "checked in"

2021-08-10 17:12 UTC, Tobias321 commented on src/de/pmdungeon/game/Controller/EntityController.java
>      }
`null` check?

2021-08-10 17:12 UTC, Tobias321 commented on src/de/pmdungeon/graphic/HUD.java
> +}
new line missing ;)

2021-08-10 17:18 UTC, Kushurando commented on src/de/pmdungeon/game/Controller/EntityController.java
>      }
I don't think it's needed here, with how I understood the code

2021-08-10 17:26 UTC, Tobias321 submitted a review, later dismissed
👍🏻

2021-08-11 09:17 UTC, Tobias321 commented
@Kushurando I've undo the README.md and pom.xml check-in with:
`git checkout origin/master README.md pom.xml`
you can then check over the changes with:
`git diff --name-status master`

2021-08-11 09:38 UTC, Tobias321 commented
@PM-Dungeon/java to checkout this branch and avoid conflicts first delete the local copy of your branch with `git branch -D constants` (the uppercase D is required), then checkout the branch again with `git checkout constants`.

2021-08-13 18:29 UTC, Tobias321 approved these changes
lgtm

2022-01-29 12:47 UTC, cagix commented
**clean-up**: @AMatutat @Tobias321 Brauchen wir das noch oder kann das zu?

2022-01-29 13:37 UTC, AMatutat commented
legacy krams, dicht

2022-01-29 13:37 UTC, closed without merging